### ISSUE TITLE
Question: How to use in webpack through babelrc

### ISSUE THREAD

**Issue by madx** [elierotenberg/babel-plugin-strip-decorator#1]
Hello,

I want to use this plugin to strip a decorator from my codebase in production but I can't find how to use it using webpack and the babel-loader, without having to manually call `stripDecorator`.

My babel config is in a `.babelrc` file, and I use `loaders: ["babel", "eslint"]` in my webpack config.

Is it possible to use this plugin like this?

**Comment by elierotenberg** [comment]
`stripDecorator` is actually not a `Plugin`, but rather a function which returns a `Plugin`. Incidentally, I don't think you can use it with `.babelrc`. But it should work fine with a regular options object, eg. using https://github.com/babel/babel-loader#options as following:

``` js
module: {
  loaders: [
    {
      test: /\.jsx?$/,
      exclude: /(node_modules|bower_components)/,
      loader: 'babel',
      query: {
        optional: ['runtime'],
        stage: 0,
        plugins: [{ transformer: stripDecorator('devDecorator'), position: 'before' }],
      }
    }
  ]
}
```

**Comment by madx** [comment]
Thanks for your answer and the provided code, it will be very useful :)

**Comment by elierotenberg** [comment]
:+1:

**Comment by madx** [comment]
I'm going to use it to implement my own plugin then so I can simply require it declaratively in babel's config :)
